### ISSUE TITLE
comments on script

### ISSUE THREAD

**Issue by julzhk** [MedicalEase/medical_consent_app#1]
* Selecting buttons: I’d be happier to not specify where relatively or what colour the buttons are. This will let the videos be re-used in other contexts without a reshoot. We might change the colours of the buttons; maybe there’ll be a red/green colourblindness switch; maybe other accessibility changes.
* We can use the same ‘choose an option’ clip each time so maybe no need to re-record it each time - if the script is ‘modular’. If there’s a variety of ‘choose your options’ texts we can use the best take each step is self-contained which is good: it’ll make re-ordering or having the user navigate easier.
* Traditionally print the script in a typewriter font & double line spaced; this lets the actors write pacing notes between the lines etc.
* If you really don’t know which lines sound better You can record different versions of the text & use the one that reads better on the day.
* maybe record a glossary too? I don’t think we will use it immediately but if we have the material it’ll be an option
* Small point: but a number and description for each section would be convenient; 
* Maybe instead of ‘tablet’ use ‘this device’? Not sure on this tbh: Actually can’t imagine the video ever being on anything smaller than a tablet..

**Comment by DrJKing** [comment]
Replies in order:

- I definitely see your point here, however how do we clarify which button to press for which option in this case? Assuming literacy, there will have to be an alternative way of identifying the buttons. If not colour, then what? I do not think the video would be used in other contexts, unless it was just an educational video in which case it would not be interactive and the final segment about the buttons (which will be a separate clip as you said) will merely not be included. However I agree re red-green colour blindness/accessibility issues... Something to flag to Dex? I need to send the scripts off this week to have them translated in time so definitely a priority to finalise.
- You are right. There are only two different options currently: yes and no; yes, no and I have further questions. We will record each one once and cut it from the rest of the script. 
- Will do - although as the actors are amateurs, I doubt that they will have any annotations!
- I think the script will be as it is. If when reading it it feels more natural to say it differently then we will adapt on the day but there will not be a multitude of ways to say what we are aiming to have said.
- Ideally this would great, I agree. Would this have to be a video though? Would audio not suffice? This would make it easier to do later down the line whenever needed. We have quite limited studio time.
- What do you mean by 'number and description for each section'?
- Good point. However I agree, I think the videos will always run on tablets for this purpose.

**Comment by julzhk** [comment]
>> buttons & colours: Something to flag to Dex? yep: Let's ask Dex
>> What do you mean by 'number and description for each section'? <<  the section headings. It's just a trivial idea tbh

I'm going to close this issue as discussed & nothing much else to do with it. And that's how comments and issues work in Github!
